###############################################################################################################################################################################
# This program takes the transformed fungal file and the percentage table as inputs. It calculates a closest taxonomic value for each genome and recover the taxonomic and
# the trophic data of each genome
###############################################################################################################################################################################

# Importation of tidyverse library
library('tidyverse')

# Importation of the percentage table generated by the program all_table_percentages.data.table
data_final <- read_delim("percentages_taxo_guild_function_unknown_data.table", delim="\t") %>% rename(JGI_ID = exp_JGI_ID)
# Importation of the transformed fungaltrait file
fungal <- read_delim("real_transformed_fungal", delim="\t")

# function for the calculation of the closest taxonomic reference of each genomes in the MycoCosm database
closest_ref <- function(data) {
  fungal1 <- data %>%
    rowwise() %>%
      mutate(
        unique_genus = list(data$Genus[data$JGI_ID != JGI_ID]),
        unique_family = list(data$Family[data$JGI_ID != JGI_ID]),
        unique_order = list(data$Order[data$JGI_ID != JGI_ID]),
        unique_class = list(data$Class[data$JGI_ID != JGI_ID]),
        unique_phylum = list(data$Phylum[data$JGI_ID != JGI_ID])
      ) %>%
      mutate(
        Closest_ref = case_when(
          Genus %in% unique_genus ~ 'genus in mycocosm',
          Family %in% unique_family ~ 'family in mycocosm',
          Order %in% unique_order ~ 'order in mycocosm',
          Class %in% unique_class ~ 'class in mycocosm',
          Phylum %in% unique_phylum ~ 'phylum in mycocosm'
      )) %>%
      select(-unique_genus, -unique_family, -unique_order, -unique_class, -unique_phylum)
  
  return(fungal1)
}

# Merging of the percentage table and taxonomic and trophic data from fungaltraits and calculation of the closest_taxonomic reference for each genomes
data_pre_complete <- data_final %>% left_join(fungal, by="JGI_ID")  %>% select(c(JGI_ID, Compare_tax, Percentages, Genus, Phylum, Class, Order, Family, primary_lifestyle, Secondary_lifestyle))
data_complete <- closest_ref(data_pre_complete) 
write_delim(data_complete, file = "data_complete", delim = "\t")
